###################################################
#
#	This makefile builds all the libraries,
#		 which can be found in the subdirectories
#
###################################################

all:
	$(MAKE) all -C conns
	$(MAKE) all -C px4remote
	$(MAKE) all -C npoint
	$(MAKE) all -C utils

clean:
	$(MAKE) clean -C conns
	$(MAKE) clean -C px4remote
	$(MAKE) clean -C npoint
	$(MAKE) clean -C utils


